<?php

namespace CRUD\PlatformBundle\Repository;

/**
 * TabAnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabAnimalRepository extends \Doctrine\ORM\EntityRepository
{
}
